@startuml
' hide the spot
' hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

!include Entities.puml!Party
!include Entities.puml!PartyRole
!include Entities.puml!PartyRelationship
!include Entities.puml!ContactMechanismType
!include Entities.puml!CommunicationEventRoleType
!include Entities.puml!ContactMechanismType
!include Entities.puml!CommunicationEvent
!include Entities.puml!CommunicationEventPurpose
!include Entities.puml!CommunicationEventPurposeType
!include Entities.puml!CommunicationEventRole
!include Entities.puml!ValidContactMechanismRole

Party  ||..|{ PartyRole
Party ||..|{ CommunicationEventRole
PartyRole ||..|{ "establishedTo" PartyRelationship
PartyRole ||..|{ "establishedFrom" PartyRelationship
PartyRelationship ||..|{ CommunicationEvent
ContactMechanismType ||..|{ CommunicationEvent
CommunicationEventRoleType ||..|{ CommunicationEventRole
CommunicationEventRoleType ||..|{ ValidContactMechanismRole
ContactMechanismType ||..|{ ValidContactMechanismRole
CommunicationEvent ||..|{ CommunicationEventPurpose
CommunicationEventPurposeType ||..|{ CommunicationEventPurpose

@enduml
