@startuml
' hide the spot
' hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

Party  ||..|{ PartyRole
Party ||..|{ CommunicationEventRole
PartyRole ||..|{ "establishedTo" PartyRelationship
PartyRole ||..|{ "establishedFrom" PartyRelationship
PartyRelationship ||..|{ CommunicationEvent
ContactMechanismType ||..|{ CommunicationEvent
CommunicationEventRoleType ||..|{ CommunicationEventRole
CommunicationEventRoleType ||..|{ ValidContactMechanismRole
ContactMechanismType ||..|{ ValidContactMechanismRole
CommunicationEvent ||..|{ CommunicationEventPurpose
CommunicationEventPurposeType ||..|{ CommunicationEventPurpose

@enduml
