@startuml
' hide the spot
' hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity WorkEffort

note top of WorkEffort : This reference will be via UUID, since work effort will be in a different database

CaseType ||..|{ Case
Case ||..|{ CaseRole
CaseRoleType ||..|{ CaseRole
Party ||..|{ CaseRole
Case ||..|{ CommunicationEvent
CommunicationEvent ||..|{ CommunicationEventPurpose
CommunicationEvent ||..|{ CommunicationEventWorkEffort
WorkEffort ||..|{ CommunicationEventWorkEffort

@enduml
