@startuml
' hide the spot
' hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

!include Entities.puml!contact_mechanism
!include Entities.puml!contact_mechanism_type
!include Entities.puml!contact_mechanism_geographic_boundary
!include Entities.puml!geographic_boundary

contact_mechanism }|..|| contact_mechanism_type
contact_mechanism }o..|| contact_mechanism_geographic_boundary

contact_mechanism_geographic_boundary }|..|| geographic_boundary
@enduml
