@startuml
' hide the spot
' hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

!include Entities.puml!contact_mechanism
!include Entities.puml!facility
!include Entities.puml!facility_role
!include Entities.puml!facility_role_type
!include Entities.puml!facility_type
!include Entities.puml!party
!include Entities.puml!party_contact_mechanism

facility ||..|{ facility_role
facility ||..|{ facility_type
facility "madeUpOf" ||..|{ "partOf" facility
facility ||..|{ facility_contact_mechanism

facility_role ||..|{ facility_role_type
facility_role ||..|{ party

facility_contact_mechanism }|..|| contact_mechanism


@enduml
