@startuml
' hide the spot
' hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

!include Entities.puml

PartyRelationship "from"  ||..|{ PartyRole
PartyRelationship "to"  ||..|{ PartyRole
PartyRelationship }|..|| PartyRelationshipType
PartyRelationship }|..|| CommunicationEvent
PartyRelationship }|..|| PriorityType
PartyRelationship }|..|| PartyRelationshipStatusType

@enduml
