@startuml
' hide the spot
' hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity Party {
}

entity PartyClassification {
}

entity PartyClassificationType {
}

entity PartyContactMechanism {
}

entity PartyContactMechanismType {
}

entity PartyId {
}

entity PartyIdType{
}

entity PartyName {

}

entity PartyNameType {

}

entity PartyRelationship {

}

entity PartyRelationshipType {

}

entity PartyRole {
}

entity PartyType {
}



Party ||..|{ PartyClassification
Party ||..|{ PartyContactMechanism
Party ||..|{ PartyId
Party ||..|{ PartyName
Party ||..|{ PartyRelationship
Party ||..|{ PartyRole
Party ||..|{ PartyType


PartyClassification ||..|{ PartyClassificationType
PartyContactMechanism ||..|{ PartyContactMechanismType
PartyId ||..|{ PartyIdType
PartyName ||..|{ PartyNameType
PartyRelationship ||..|{ PartyRelationshipType
PartyRole ||..|{ PartyRoleType


@enduml
