@startuml
' hide the spot
' hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

!include Entities.puml!Party
!include Entities.puml!PartyClassification
!include Entities.puml!PartyContactMechanism
!include Entities.puml!PartyId
!include Entities.puml!PartyName
!include Entities.puml!PartyRelationship
!include Entities.puml!PartyRole
!include Entities.puml!PartyType

Party ||..|{ PartyClassification
Party ||..|{ PartyContactMechanism
Party ||..|{ PartyId
Party ||..|{ PartyName
Party ||..|{ PartyRelationship
Party ||..|{ PartyRole
Party ||..|{ PartyType


PartyClassification ||..|{ PartyClassificationType
PartyContactMechanism ||..|{ PartyContactMechanismType
PartyId ||..|{ PartyIdType
PartyName ||..|{ PartyNameType
PartyRelationship ||..|{ PartyRelationshipType
PartyRole ||..|{ PartyRoleType


@enduml
