@startuml
' hide the spot
' hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

' Define only the entities used in this diagram
entity party {}
entity party_role {}
entity party_role_type {}

party ||..|{ party_role
party_role_type ||..|{ party_role

@enduml
