@startuml
' hide the spot
' hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

!include Entities.puml!party
!include Entities.puml!party_contact_mechanism
!include Entities.puml!contact_mechanism
!include Entities.puml!contact_mechanism_type
!include Entities.puml!party_contact_mechanism_purpose
!include Entities.puml!party_contact_mechanism_purpose_type

party_contact_mechanism }|..|| contact_mechanism
party_contact_mechanism }|..|| party
party_contact_mechanism ||..|{ party_contact_mechanism_purpose

contact_mechanism }|..|| contact_mechanism_type
party_contact_mechanism_purpose }|..|| party_contact_mechanism_purpose_type


@enduml
