@startuml
' hide the spot
' hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity Citizenship {
}

entity Country {
}

entity GenderType {
}

entity MaritalStatus {
}

entity MaritalStatusType {
}

entity Passport {
}

entity Person {
}

entity PersonName {
}

entity PersonNameType {
}

entity PhysicalCharacteristic {
}

entity PhysicalCharacteristicType {
}

Person ||..|{ MaritalStatus
Person ||..|{ PhysicalCharacteristic
Person ||..|{ PersonName
Person ||..|{ Citizenship
Person }|..|| GenderType
MaritalStatusType ||..|{ MaritalStatus
PhysicalCharacteristicType ||..|{ PhysicalCharacteristic
PersonNameType ||..|{ PersonName
Country ||..|{ Citizenship
Passport ||..|{ Citizenship

@enduml
