@startuml
' hide the spot
' hide circle

' avoid problems with angled crows feet
skinparam linetype ortho
!include Entities.puml!party
!include Entities.puml!party_role
!include Entities.puml!party_role_type
!include Entities.puml!party_relationship

party ||..|{ party_role
party_role_type ||..|{ party_role
party_relationship "from"  ||..|{ party_role
party_relationship "to"  ||..|{ party_role
party_relationship_type ||..|{ party_relationship
@enduml
